// <auto-generated />
using System;
using Esatto.Outreach.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Esatto.Outreach.Infrastructure.Migrations
{
    [DbContext(typeof(OutreachDbContext))]
    [Migration("20251114064954_AddSoftCompanyDataWithProspectRelation")]
    partial class AddSoftCompanyDataWithProspectRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.HardCompanyData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CasesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyOverview")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndustriesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyFactsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ResearchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServicesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResearchedAt");

                    b.ToTable("hard_company_data", (string)null);
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.Prospect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HardCompanyDataId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastOpenAIResponseId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedinUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MailBodyHTML")
                        .HasColumnType("text");

                    b.Property<string>("MailBodyPlain")
                        .HasColumnType("text");

                    b.Property<string>("MailTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SoftCompanyDataId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName");

                    b.HasIndex("Domain");

                    b.HasIndex("HardCompanyDataId");

                    b.HasIndex("MailTitle");

                    b.HasIndex("SoftCompanyDataId");

                    b.HasIndex("Status", "CreatedUtc");

                    b.ToTable("prospects", (string)null);
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.SoftCompanyData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HooksJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewsItemsJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProspectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecentEventsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ResearchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SocialActivityJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProspectId")
                        .IsUnique();

                    b.HasIndex("ResearchedAt");

                    b.ToTable("soft_company_data", (string)null);
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.Prospect", b =>
                {
                    b.HasOne("Esatto.Outreach.Domain.Entities.HardCompanyData", "HardCompanyData")
                        .WithMany()
                        .HasForeignKey("HardCompanyDataId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HardCompanyData");
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.SoftCompanyData", b =>
                {
                    b.HasOne("Esatto.Outreach.Domain.Entities.Prospect", "Prospect")
                        .WithOne("SoftCompanyData")
                        .HasForeignKey("Esatto.Outreach.Domain.Entities.SoftCompanyData", "ProspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.Prospect", b =>
                {
                    b.Navigation("SoftCompanyData");
                });
#pragma warning restore 612, 618
        }
    }
}
