// <auto-generated />
using System;
using System.Collections.Generic;
using Esatto.Outreach.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Esatto.Outreach.Infrastructure.Migrations
{
    [DbContext(typeof(OutreachDbContext))]
    [Migration("20260116142854_RefactorEntityIntelligenceStructure")]
    partial class RefactorEntityIntelligenceStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.ContactPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PersonalHooksJson")
                        .HasColumnType("text");

                    b.Property<string>("PersonalNewsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("ProspectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProspectId");

                    b.ToTable("ContactPersons");
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.EntityIntelligence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnrichmentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProspectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ResearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SummarizedContext")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProspectId")
                        .IsUnique();

                    b.HasIndex("ResearchedAt");

                    b.ToTable("entity_intelligence", (string)null);
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.GenerateEmailPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("generate_email_prompts", (string)null);
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.HardCompanyData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CasesJson")
                        .HasColumnType("text");

                    b.Property<string>("CompanyOverview")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IndustriesJson")
                        .HasColumnType("text");

                    b.Property<string>("KeyFactsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("ResearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServicesJson")
                        .HasColumnType("text");

                    b.Property<string>("SourcesJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResearchedAt");

                    b.ToTable("hard_company_data", (string)null);
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.Prospect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<string>("Addresses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("CapsuleCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CapsuleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CapsuleUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomFields")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EmailAddresses")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("EntityIntelligenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HardCompanyDataId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastContactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastOpenAIResponseId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MailBodyHTML")
                        .HasColumnType("text");

                    b.Property<string>("MailBodyPlain")
                        .HasColumnType("text");

                    b.Property<string>("MailTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("PhoneNumbers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PictureURL")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Websites")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CapsuleId")
                        .IsUnique()
                        .HasFilter("\"CapsuleId\" IS NOT NULL");

                    b.HasIndex("EntityIntelligenceId");

                    b.HasIndex("HardCompanyDataId");

                    b.HasIndex("IsPending");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("IsPending", "CreatedUtc");

                    b.HasIndex("OwnerId", "Status");

                    b.HasIndex("Status", "CreatedUtc");

                    b.ToTable("prospects", (string)null);
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.ContactPerson", b =>
                {
                    b.HasOne("Esatto.Outreach.Domain.Entities.Prospect", "Prospect")
                        .WithMany("ContactPersons")
                        .HasForeignKey("ProspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.EntityIntelligence", b =>
                {
                    b.HasOne("Esatto.Outreach.Domain.Entities.Prospect", "Prospect")
                        .WithOne("EntityIntelligence")
                        .HasForeignKey("Esatto.Outreach.Domain.Entities.EntityIntelligence", "ProspectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Esatto.Outreach.Domain.ValueObjects.CompanyEnrichmentResult", "EnrichedData", b1 =>
                        {
                            b1.Property<Guid>("EntityIntelligenceId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<string>>("MethodologyUsed")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.PrimitiveCollection<List<string>>("OpenQuestions")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.HasKey("EntityIntelligenceId");

                            b1.ToTable("entity_intelligence");

                            b1.ToJson("EnrichedData");

                            b1.WithOwner()
                                .HasForeignKey("EntityIntelligenceId");

                            b1.OwnsOne("Esatto.Outreach.Domain.ValueObjects.BusinessChallenges", "Challenges", b2 =>
                                {
                                    b2.Property<Guid>("CompanyEnrichmentResultEntityIntelligenceId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("CompanyEnrichmentResultEntityIntelligenceId");

                                    b2.ToTable("entity_intelligence");

                                    b2.WithOwner()
                                        .HasForeignKey("CompanyEnrichmentResultEntityIntelligenceId");

                                    b2.OwnsMany("Esatto.Outreach.Domain.ValueObjects.ConfirmedChallenge", "Confirmed", b3 =>
                                        {
                                            b3.Property<Guid>("BusinessChallengesCompanyEnrichmentResultEntityIntelligenceId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<string>("ChallengeDescription")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<string>("EvidenceSnippet")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<string>("SourceUrl")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.HasKey("BusinessChallengesCompanyEnrichmentResultEntityIntelligenceId", "__synthesizedOrdinal");

                                            b3.ToTable("entity_intelligence");

                                            b3.WithOwner()
                                                .HasForeignKey("BusinessChallengesCompanyEnrichmentResultEntityIntelligenceId");
                                        });

                                    b2.OwnsMany("Esatto.Outreach.Domain.ValueObjects.InferredChallenge", "Inferred", b3 =>
                                        {
                                            b3.Property<Guid>("BusinessChallengesCompanyEnrichmentResultEntityIntelligenceId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            b3.Property<string>("ChallengeDescription")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<string>("ConfidenceLevel")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.Property<string>("Reasoning")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.HasKey("BusinessChallengesCompanyEnrichmentResultEntityIntelligenceId", "__synthesizedOrdinal");

                                            b3.ToTable("entity_intelligence");

                                            b3.WithOwner()
                                                .HasForeignKey("BusinessChallengesCompanyEnrichmentResultEntityIntelligenceId");
                                        });

                                    b2.Navigation("Confirmed");

                                    b2.Navigation("Inferred");
                                });

                            b1.OwnsMany("Esatto.Outreach.Domain.ValueObjects.CompanyOutreachHook", "OutreachHooks", b2 =>
                                {
                                    b2.Property<Guid>("CompanyEnrichmentResultEntityIntelligenceId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("ConfidenceLevel")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Date")
                                        .HasColumnType("text");

                                    b2.Property<string>("HookDescription")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Source")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("WhyItMatters")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("CompanyEnrichmentResultEntityIntelligenceId", "__synthesizedOrdinal");

                                    b2.ToTable("entity_intelligence");

                                    b2.WithOwner()
                                        .HasForeignKey("CompanyEnrichmentResultEntityIntelligenceId");
                                });

                            b1.OwnsOne("Esatto.Outreach.Domain.ValueObjects.CompanySnapshot", "Snapshot", b2 =>
                                {
                                    b2.Property<Guid>("CompanyEnrichmentResultEntityIntelligenceId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("HowTheyOperate")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("MarketPosition")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("TargetCustomer")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("WhatTheyDo")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("CompanyEnrichmentResultEntityIntelligenceId");

                                    b2.ToTable("entity_intelligence");

                                    b2.WithOwner()
                                        .HasForeignKey("CompanyEnrichmentResultEntityIntelligenceId");
                                });

                            b1.OwnsMany("Esatto.Outreach.Domain.ValueObjects.EvidenceSource", "EvidenceLog", b2 =>
                                {
                                    b2.Property<Guid>("CompanyEnrichmentResultEntityIntelligenceId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Date")
                                        .HasColumnType("text");

                                    b2.Property<string>("KeyFactExtracted")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Publisher")
                                        .HasColumnType("text");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("CompanyEnrichmentResultEntityIntelligenceId", "__synthesizedOrdinal");

                                    b2.ToTable("entity_intelligence");

                                    b2.WithOwner()
                                        .HasForeignKey("CompanyEnrichmentResultEntityIntelligenceId");
                                });

                            b1.OwnsOne("Esatto.Outreach.Domain.ValueObjects.SolutionRelevantProfile", "Profile", b2 =>
                                {
                                    b2.Property<Guid>("CompanyEnrichmentResultEntityIntelligenceId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("BusinessModel")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("ComplianceContext")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("CustomerType")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("DataIntegrationNeeds")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<Dictionary<string, string>>("FieldConfidence")
                                        .IsRequired()
                                        .HasColumnType("hstore");

                                    b2.Property<string>("NotableConstraints")
                                        .HasColumnType("text");

                                    b2.Property<string>("OperationalComplexity")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("OperationalComplexityReasoning")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("ProcessMaturity")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("RevenueMotion")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("ScalingStage")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("TechnologyPosture")
                                        .HasColumnType("text");

                                    b2.HasKey("CompanyEnrichmentResultEntityIntelligenceId");

                                    b2.ToTable("entity_intelligence");

                                    b2.WithOwner()
                                        .HasForeignKey("CompanyEnrichmentResultEntityIntelligenceId");
                                });

                            b1.Navigation("Challenges")
                                .IsRequired();

                            b1.Navigation("EvidenceLog");

                            b1.Navigation("OutreachHooks");

                            b1.Navigation("Profile")
                                .IsRequired();

                            b1.Navigation("Snapshot")
                                .IsRequired();
                        });

                    b.Navigation("EnrichedData");

                    b.Navigation("Prospect");
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.GenerateEmailPrompt", b =>
                {
                    b.HasOne("Esatto.Outreach.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.Prospect", b =>
                {
                    b.HasOne("Esatto.Outreach.Domain.Entities.HardCompanyData", "HardCompanyData")
                        .WithMany()
                        .HasForeignKey("HardCompanyDataId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Esatto.Outreach.Domain.Entities.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HardCompanyData");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Esatto.Outreach.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Esatto.Outreach.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Esatto.Outreach.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Esatto.Outreach.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Esatto.Outreach.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Esatto.Outreach.Domain.Entities.Prospect", b =>
                {
                    b.Navigation("ContactPersons");

                    b.Navigation("EntityIntelligence");
                });
#pragma warning restore 612, 618
        }
    }
}
